### ISSUE TITLE
(EXAMPLE) Need to modify Autonomous Opmode for Red Side Position 2

### ISSUE THREAD

**Issue by Bartacus88** [Bartacus88/FtcRobotController#1]
The team is asking that the Programming team look at the Autonomous Opmode for Red Side Position 2.  The team has tested both autonomous modes from their respective starting positions on the field.  The  Autonomous Opmode for Red Side Position 2 appears to function exactly Autonomous Opmode for Red Side Position 2.

The issue with Autonomous Opmode for Red Side Position 2 acting the same as Autonomous Opmode for Red Side Position 1 is that the robot delivers the wobble goal 24 inches to the left. 

To replicate the issue:
1) Place robot on Red Side Position 1.
2) Run robot with Autonomous Opmode for Red Side Position 1.
3) Note that robot delivers wobble goal correctly. 
4) re-place robot on Red Side Position 2.
2) Run robot with Autonomous Opmode for Red Side Position 2.
3) Note that robot delivers wobble goal 24 inches to the left of the intended target. 

Team is willing to update issue with videos of the two Opmodes.

**Comment by ColumbusFTCsoftware** [comment]
sample issue, no change needed.
