### ISSUE TITLE
Shooter - forward and backward

### ISSUE THREAD

**Issue by ColumbusFTCsoftware** [Bartacus88/FtcRobotController#2]
Need to be able to move the rings forward and backward -- this is to prevent the rings from staying jammed in the autoloader.

**Comment by Bartacus88** [comment]
This was covered in Issue 5's latest update: https://github.com/Bartacus88/FtcRobotController/issues/5#issuecomment-761836694

Recommend closure of issue at next virtual practice.

**Comment by Bartacus88** [comment]
Shooter can reverse/forward for the last three meets.  Closing issue.  See issue 7 for further tuning. https://github.com/Bartacus88/FtcRobotController/issues/7
