### ISSUE TITLE
Intake.  Forward and backward control is needed

### ISSUE THREAD

**Issue by ColumbusFTCsoftware** [Bartacus88/FtcRobotController#3]
To prevent rings from getting jammed in the intake, need to make it able to go in reverse also.

**Comment by ColumbusFTCsoftware** [comment]
Same milestone as issue #2

**Comment by Bartacus88** [comment]
Intake can reverse/forward for the last three meets.  Closing issue.  See issue 7 for further tuning. https://github.com/Bartacus88/FtcRobotController/issues/7
