### ISSUE TITLE
Setup a second controller for the co-driver

### ISSUE THREAD

**Issue by ColumbusFTCsoftware** [Bartacus88/FtcRobotController#4]
Self explanatory.   Proposal:
Co-driver is in control of 
1) intake
2) shooter
3) wobble goal manipulation.
(by reduction, driver #1 is the Uber operator)

**Comment by Bartacus88** [comment]
While not a permanent solution, Issue 7 (Controller UIX Improvement) updates, positively impacted second controller setup. See: https://github.com/Bartacus88/FtcRobotController/issues/7#issuecomment-757498700

gampad2.right_trigger = Intake
gampad2.x = Shooter (at intakes power)
gampad2.a = Lift Wobble Arm
gamepad2.b = Lower Wobble Arm

**Comment by Bartacus88** [comment]
Better UIX has been created. Closing issue. See issue 7 if any further work is needed. https://github.com/Bartacus88/FtcRobotController/issues/7
