### ISSUE TITLE
Gradient shooting power for rings

### ISSUE THREAD

**Issue by ColumbusFTCsoftware** [Bartacus88/FtcRobotController#5]
Allow driver #2 to adjust motor power for shooter so rings get about where we want them.

**Comment by 50N40W** [comment]
Based on 22 Dec 2020 meeting, proposal has these phases.
1. Driver station 1, left trigger, proportional control of shooter motor.
2. Driver station 1, right trigger, proportional _reverse_ control of shooter motor.  Max power at about -25% maybe?
3. In event left and right triggers are both engaged, ignore the right (reverse)
4. Follow-on.  when Driver Station #1 left trigger is pressed, engage the loader motor at some proportional power setting This will cause the particles to be loaded into the breach while the shooter is engaged.
5. When driver station 1 right trigger is pressed, engage the loader motor in reverse at some TBD lower rate of speed.   As with the shooter motor, the left trigger shall be the winner if both triggers are pressed simultaneously.
6. Follow-on 2, (proposed) use a servo to create a barrier between the end of the loader and the breech of the shooter.  The barrier is ACTIVE when shooter power is between -4% and 10%.  When shooter power is outside of that range, the barrier is INACTIVE, and allows particles to transit the gap between loader and shooter.

**Comment by Bartacus88** [comment]
On 1/14 and 1/16 practices we tested gamepad2.right_trigger for running intake forward (proportionally) and gampad2.a to run the shooter at the same power as intake. Gampad2.left_trigger for moving the intake and shooter backwards (proportionally). 

We initially limited backwards power to 25% but this was not enough, and we eventually increased the power to up to 75%.

Lastly we found that, when the bot had more than one ring, the first ring would not launch far.  Therefore we added a minimum 20% power when gamepad2.a was pressed, increasing if the intake's power (gamepad2.right_trigger) was higher.

**Comment by Bartacus88** [comment]
https://github.com/Bartacus88/FtcRobotController/issues/7#issuecomment-797695094
Issue 7 has the update for our preferred method to control intake power (RT/LT - proportional on driver controller) and shooter (D-Pad co-driver controller. Marking this issue closed. Further needs should be addressed in issue 7.
