### ISSUE TITLE
Joystick mapping: Swap rotate vs crab

### ISSUE THREAD

**Issue by 50N40W** [Bartacus88/FtcRobotController#9]
The rotate is currently on the same stick as fore-aft, and it should be on a different joystick.   Also the crab is on a different joystick from the fore-aft command and should be on the same joystick.  That is, the rotate and the crab inputs should be swapped.

**Comment by Bartacus88** [comment]
I have added "JK Drive Opmode Sideways JS Swapped" as an opmode to address these concerns.  I have also asked the build team to look at this new opmode.

**Comment by Bartacus88** [comment]
"JK Drive Opmode Sideways JS Swapped" has been used in three meets.  Closing issue.
